### ISSUE TITLE
vin.details: 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by lecmarohom** [idlesign/vininfo#6]
Does this part of the quick guide supposed to return something?

**details = vin.details**

**Comment by idlesign** [comment]
Yes, if details (additional information) is available for a brand.
https://github.com/idlesign/vininfo/blob/master/tests/test_lada.py#L28

**Comment by cubelos** [comment]
Hello. Not sure if I should have opened a new issue or continue in this one.

I was trying both the cli and the python code example, and I'm having issues with the details.

When using the cli this error prompts:
`Details:
Traceback (most recent call last):
  File "...bin/vininfo", line 8, in <module>
    sys.exit(main())
  File "...lib/python3.6/site-packages/vininfo/cli.py", line 51, in main
    entry_point(obj={})
  File "...lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "...lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "...lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "...lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "...lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "...lib/python3.6/site-packages/vininfo/cli.py", line 35, in show
    out(details)
  File "...lib/python3.6/site-packages/vininfo/cli.py", line 24, in out
    for k, v in annotatable.annotate().items():
  File "...lib/python3.6/site-packages/vininfo/common.py", line 17, in annotate
    value = getattr(self, attr_name, no_attr)
  File "...lib/python3.6/site-packages/vininfo/details/_base.py", line 52, in __get__
    return DetailWrapper(instance, self)
  File "...lib/python3.6/site-packages/vininfo/details/_base.py", line 20, in __init__
    attr_name, attr_idx = detail.source
TypeError: 'NoneType' object is not iterable
`

When using the python example code, nothing prompts and I only success to access the details when using directly (details.body.name, details.engine.name...), but if I try to annotate() the details the same error as before appears, and the same happens when accessing with the "details.body.name" approach a missing information not detected in the actual VIN.

Do you have any idea how could I solve it? Am I missing something? Thanks!

**Comment by idlesign** [comment]
Let's try to investigate.
Please provide VIN leading to the error and code you're trying to execute.

**Comment by cubelos** [comment]
Thanks for the fast reply.

It happens with almost all the VIN numbers I try, not sure why (it doesn't happen with the example VIN you provide). For instance, with this Renaul VIN 'VF1KG1PBE34488860' or '9FB5SRC9BJM728632'... If you need more examples please let me know.

As mentioned, it looks like for these VINs the detail info is not correctly identified and the code then breaks (both with the CLI and the python code). Please, find below the code I'm trying to execute:

`from vininfo import Vin
import click
vin = Vin('VF1KG1PBE34488860')

annotated = vin.annotate()
# I am not able to access the details below, the annotate() method does not work.
details = vin.details

print(annotated)

# With this dirty code I succeed to print the details of cars where the details are correctly identified (as with the VIN you provide as example) but it still breaks for other VINs
details_final = {}
if details is not None:
    details_final['Body'] = details.body.name 
    details_final['Engine'] = details.engine.name
    details_final['Model'] = details.model.name
    details_final['Plant'] = details.plant.name
    details_final['Serial'] = details.serial.name

    details_cleaned = {k: v for k, v in details_final.items() if v is not None}
    print(details_cleaned)

print(vin.verify_checksum() )`


Thanks again

**Comment by idlesign** [comment]
This one if now seem to be fixed in 1.4.1 — give it a try.

Thank you for the report! 
Feel free to reopen if needed.

**Comment by cubelos** [comment]
Wow, nice work there!! Thank you
